"""Async, subject-scoped ChatGPT OAuth and subscription transport."""

from .client import SubscriptionAI, create_client
from .loopback import login_with_loopback, wait_for_loopback_callback
from .protocol import PROTOCOL, ProtocolConfig
from .session import AuthSession
from .stores import (
    FileCredentialStore,
    MemoryCredentialStore,
    create_file_store,
    create_memory_store,
)
from .types import (
    AuthError,
    ChatGPTOAuthError,
    CompareAndSwapResult,
    CredentialStore,
    DeviceLogin,
    DisabledError,
    JsonValue,
    PendingLogin,
    RateLimitError,
    RateLimitSnapshot,
    RateLimitWindow,
    ReauthRequired,
    ResponseContent,
    ResponseEvent,
    ResponseRequest,
    ResponseResult,
    Session,
    StateMismatchError,
    StoreError,
    TokenRefreshError,
    TokenSet,
    TransportError,
)

__all__ = [
    "PROTOCOL",
    "AuthError",
    "AuthSession",
    "ChatGPTOAuthError",
    "CompareAndSwapResult",
    "CredentialStore",
    "DeviceLogin",
    "DisabledError",
    "FileCredentialStore",
    "JsonValue",
    "MemoryCredentialStore",
    "PendingLogin",
    "ProtocolConfig",
    "RateLimitError",
    "RateLimitSnapshot",
    "RateLimitWindow",
    "ReauthRequired",
    "ResponseContent",
    "ResponseEvent",
    "ResponseRequest",
    "ResponseResult",
    "Session",
    "StateMismatchError",
    "StoreError",
    "SubscriptionAI",
    "TokenRefreshError",
    "TokenSet",
    "TransportError",
    "create_client",
    "create_file_store",
    "create_memory_store",
    "login_with_loopback",
    "wait_for_loopback_callback",
]
